# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myaws < Formula
  desc "A human friendly AWS CLI written in Go"
  homepage "https://github.com/minamijoyo/myaws"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/myaws/releases/download/v0.4.0/myaws_v0.4.0_darwin_amd64.tar.gz"
      sha256 "74b3c4a06d262f09fb4934e3cfe005f70ee46d5c138519c0a08b58ee6f5bb886"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/minamijoyo/myaws/releases/download/v0.4.0/myaws_v0.4.0_linux_amd64.tar.gz"
      sha256 "c1e26abb0fef9c9ef77af6679237fe2aba78ae8a52d583ebfa8ecf5c0dc40319"
    end
  end

  def install
    bin.install "myaws"
    output = Utils.popen_read("#{bin}/myaws completion bash")
    (bash_completion/"myaws").write output
    output = Utils.popen_read("#{bin}/myaws completion zsh")
    (zsh_completion/"_myaws").write output
  end

  test do
    system "#{bin}/myaws version"
  end
end
